Repository uprm-inso4117-2024-2025-s2/semester-project-petfinder, pull requests merged in 2025-03, with the labels that each got.

#161 Added live location functionality to map
  Pet-Finder/app/(tabs)/MapScreen.tsx
  Pet-Finder/package-lock.json
  Pet-Finder/package.json
Labels: Interactive Map Team

#159 Lost Pet Report Screen implemented
  .vscode/settings.json
  Pet-Finder/app/(tabs)/ReportScreen.tsx
  Pet-Finder/assets/images/Pet_Finder_Assets/alarm.png
  Pet-Finder/assets/images/Pet_Finder_Assets/arrow.png
  Pet-Finder/package-lock.json
  Pet-Finder/package.json
Labels: User-to-User Interactions Team

#160 121 landing page
  Pet-Finder/app/(tabs)/LandingScreen.tsx
  Pet-Finder/app/(tabs)/index.tsx
  Pet-Finder/app/+not-found.tsx
  Pet-Finder/screens/LandingScreen.js
Labels: User-to-User Interactions Team

#198 Added Header and Footer to the Landing Page
  Pet-Finder/app/(tabs)/LandingScreen.tsx
  Pet-Finder/screens/LandingScreen.js
Labels: User-to-User Interactions Team

#208 Report Screen Modifications (Tasks #192, #188, #186, #132)
  Pet-Finder/app/(tabs)/ReportScreen.tsx
  Pet-Finder/package-lock.json
  Pet-Finder/package.json
  Pet-Finder/test/ReportScreen.test.tsx
Labels: User-to-User Interactions Team

#206 Live Location Testing
  Pet-Finder/components/__tests__/location.test.js
Labels: Interactive Map Team

#213 Refactored Map Screen Implementation
  Pet-Finder/app/(tabs)/MapScreen.tsx
Labels: Interactive Map Team

#166 Authentication
  Pet-Finder/app/(tabs)/Enable2FAScreen.tsx
  Pet-Finder/app/(tabs)/LoginScreen.tsx
  Pet-Finder/app/(tabs)/SignUp.tsx
  Pet-Finder/package-lock.json
  Pet-Finder/package.json
  Pet-Finder/utils/authUtil.js
  node_modules/fsevents/LICENSE
  node_modules/fsevents/README.md
  node_modules/fsevents/fsevents.d.ts
  node_modules/fsevents/fsevents.js
  node_modules/fsevents/fsevents.node
  node_modules/fsevents/package.json
Labels: User Profile / Authentication Team
